### ISSUE TITLE
Property 'value' does not exist on type 'number'.  TS2339

### ISSUE THREAD

**Issue by andredourado** [SampaioLeal/material-ui-numeric-input#1]
Em um projeto typescript, copiando e colando o exemplo, é exibido esse erro. Property 'value' does not exist on type 'number'. TS2339 #1

Se eu apenas uso:

onChange={(e) => console.log(e)}

O valor é exibido normalmente.

**Comment by SampaioLeal** [comment]
Opa, bom dia, realmente o exemplo está desatualizado
Foi simplificado o retorno do componente para expor apenas o valor numérico na proriedade onChange

Dá uma olhadinha no exemplo funcionando: https://github.com/SampaioLeal/material-ui-numeric-input/blob/master/example/src/App.tsx#L8

O erro indica que o parâmetro `e` é um número, por que ele definitivamente é o valor do input. O problema que me deparei foi que a propriedade `e.target.value` trata-se do valor com máscara.

**Comment by SampaioLeal** [comment]
Irei atualizar o exemplo no README

**Comment by andredourado** [comment]
Amigo, muito bom seu componente. Vou passar a usá-lo em todos meus projetos. Muito obrigado mesmo.

**Comment by SampaioLeal** [comment]
Muitíssimo obrigado. Já deixei anotado aqui, e a próxima atualização vai melhorar essa integração com libs de formulários (unform, formik...), expondo o evento e o valor numérico
