### ISSUE TITLE
Cannot find name 'HTMLNumericElement'

### ISSUE THREAD

**Issue by santanna106** [SampaioLeal/material-ui-numeric-input#10]
I installed material-ui-numeric-input in my ReactJs project. But, the project did not find the 'HTMLNumericElement'. I had to define it on the page that the NumericInput component was used for the page to work. Could I have made a mistake?

**Comment by SampaioLeal** [comment]
can you try the new version? 3.1.1

**Comment by santanna106** [comment]
I am using the "material-ui-numeric-input": "^3.1.0" version.

**Comment by santanna106** [comment]
Yes, I can test and report to you.

**Comment by santanna106** [comment]
With update to version 3.1.1 the probleme resolved
