### ISSUE TITLE
Mensagem de aviso - React 17.0.2

### ISSUE THREAD

**Issue by luanfvieira** [SampaioLeal/material-ui-numeric-input#2]
Versão:
"react-dom": "^17.0.2",
"react": "^17.0.2"",

Mensagem de aviso:

Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: CurrencyInput

**Comment by SampaioLeal** [comment]
Opa, tudo bom? Eu tinha planos de fazer nosso próprio CurrencyInput, mas infelizmente ele é uma dependência do projeto.
Se tiver disposto a ajudar a gente poderia entrar em contato e discutir como iniciar
