### ISSUE TITLE
I need empty value 

### ISSUE THREAD

**Issue by gfigueroaalmera** [SampaioLeal/material-ui-numeric-input#6]
I this moment  when put "" to add 0.

**Comment by SampaioLeal** [comment]
I'm working on a new way to show the input value without other libs
Some people want to show some zeros based on precision: Value 0; Precision 2; Input "0,00"
And you want to show empty input

What you think about a prop with a name like `enableEmpty` that handles empty string values?

**Comment by gfigueroaalmera** [comment]
Yeah it is a good idea

**Comment by SampaioLeal** [comment]
Nice, so i believe i can achieve this at next week :)
so busy these days

**Comment by gfigueroaalmera** [comment]
Ok thank you, I will analize and could be create Pull request

**Comment by SampaioLeal** [comment]
Can you test v3.0.1?

**Comment by SampaioLeal** [comment]
I'm using `null` as empty value cause i think that mix string and number could be a bad idea

**Comment by gfigueroaalmera** [comment]
I realized to pr checking, the lib you is using has allowEmpty

**Comment by gfigueroaalmera** [comment]
I didn't see the new update

**Comment by SampaioLeal** [comment]
https://github.com/SampaioLeal/material-ui-numeric-input/tree/v3.0.1

**Comment by gfigueroaalmera** [comment]
Yeah but  I need the field validate required

**Comment by gfigueroaalmera** [comment]
I want select and delete and empty chain

**Comment by SampaioLeal** [comment]
> Yeah but I need the field validate required

you can check if the value is different of `null`

**Comment by gfigueroaalmera** [comment]
I understood 
thank you very much
